import csv
import io
import uuid
from datetime import datetime, timezone

def _na(value, fmt=None):
    if value is None or value == "" or value == [] or value == {}:
        return "N/A"
    if fmt:
        try:
            return fmt(value)
        except Exception:
            return str(value)
    return str(value)


def _fmt_ts(raw):
    if not raw or raw == "N/A":
        return "N/A"
    s = str(raw).strip()

    import re as _re
    s = _re.sub(r'(\.\d{6})\d+', r'\1', s)
    s = _re.sub(r'[+-]00:?00$', 'Z', s)
    has_tz = s.endswith('Z')
    s_clean = _re.sub(r'[+-]\d{2}:?\d{2}$', '', s) if not has_tz else s

    for fmt in (
        "%Y-%m-%dT%H:%M:%S.%fZ",
        "%Y-%m-%dT%H:%M:%SZ",
        "%Y-%m-%dT%H:%M:%S.%f",
        "%Y-%m-%dT%H:%M:%S",
        "%Y-%m-%d %H:%M:%S.%f",
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d %H:%M",
        "%Y-%m-%d",
    ):
        target = s if fmt.endswith('Z') else s_clean
        try:
            dt = datetime.strptime(target, fmt)
            suffix = " UTC" if has_tz else ""
            return dt.strftime(f"%-d %b %Y, %H:%M:%S{suffix}")
        except ValueError:
            continue
    return str(raw)  # return original if no format matched


def _sev_label(sev_int):
    mapping = {1: "HIGH", 2: "MEDIUM", 3: "LOW"}
    return mapping.get(int(sev_int) if sev_int is not None else 3, "LOW")


def _now_utc():
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _dedup_alerts(flagged_entities):
    """Extract, deduplicate and chronologically sort all Suricata alerts."""
    all_alerts = []
    for entity in (flagged_entities or []):
        for alert in entity.get("alerts", []):
            alert = dict(alert)
            alert["_entity_ip"] = entity.get("ip", "N/A")
            all_alerts.append(alert)
    all_alerts.sort(key=lambda a: a.get("timestamp") or "")
    seen = set()
    deduped = []
    for a in all_alerts:
        key = (a.get("signature"), a.get("src_ip"), a.get("timestamp"))
        if key not in seen:
            seen.add(key)
            deduped.append(a)
    return deduped


# ===========================================================================
# CSV EXPORT
# ===========================================================================

def build_csv(data: dict, pcap_filename: str = "unknown.pcap") -> bytes:
    buf = io.StringIO()
    writer = csv.writer(buf, quoting=csv.QUOTE_MINIMAL)
    report_id = str(uuid.uuid4())
    timestamp = _now_utc()

    def section(title):
        writer.writerow([])
        writer.writerow([f"=== {title} ==="])

    # ---- REPORT METADATA ----
    section("REPORT METADATA")
    writer.writerow(["Report ID", report_id])
    writer.writerow(["Generated At (UTC)", timestamp])
    writer.writerow(["PCAP File", _na(pcap_filename)])
    writer.writerow(["Generated By", "Adaptive PCAP Analysis System v1.0"])
    writer.writerow(["Classification", "CONFIDENTIAL: For Authorized SOC Use Only"])

    # ---- CAPTURE METADATA ----
    section("CAPTURE METADATA")
    meta = data.get("capture_metadata", {})
    writer.writerow(["Field", "Value"])
    writer.writerow(["PCAP Format", _na(meta.get("pcap_format"))])
    writer.writerow(["File Size (KB)", _na(meta.get("file_size_kb"))])
    writer.writerow(["Capture Duration (s)", _na(meta.get("capture_duration"))])
    writer.writerow(["Start Time", _fmt_ts(meta.get("start_time"))])
    writer.writerow(["End Time", _fmt_ts(meta.get("end_time"))])
    writer.writerow(["Snapshot Length (bytes)", _na(meta.get("snapshot_length"))])

    # ---- SUMMARY METRICS ----
    section("SUMMARY METRICS")
    writer.writerow(["Metric", "Value"])
    writer.writerow(["Total Packets", _na(data.get("total_packets"))])
    writer.writerow(["Valid Packets", _na(data.get("valid_packets"))])
    writer.writerow(["Malformed Packets", _na(data.get("malformed_packets"))])
    writer.writerow(["Fragmented Packets", _na(data.get("fragmented_packets"))])
    writer.writerow(["Jumbo Frames (>1500B)", _na(data.get("jumbo_frames"))])
    writer.writerow(["Packets Per Second", _na(data.get("packets_per_second"))])
    pkt = data.get("packet_size", {})
    writer.writerow(["Packet Size — Min (bytes)", _na(pkt.get("min"))])
    writer.writerow(["Packet Size — Max (bytes)", _na(pkt.get("max"))])
    writer.writerow(["Packet Size — Avg (bytes)", _na(pkt.get("avg"))])

    # ---- PACKET SIZE HISTOGRAM ----
    section("PACKET SIZE HISTOGRAM")
    hist = data.get("packet_size_histogram", {})
    if hist:
        writer.writerow(["Bin", "Packet Count"])
        for bin_label, count in hist.items():
            writer.writerow([bin_label, count])
    else:
        writer.writerow(["No histogram data available"])

    # ---- IP ADDRESS DISTRIBUTION ----
    section("IP ADDRESS DISTRIBUTION")
    ip_dist = data.get("ip_distribution", {})
    if ip_dist:
        writer.writerow(["IP Class", "Packet Count"])
        for cls, cnt in ip_dist.items():
            writer.writerow([cls, cnt])
    else:
        writer.writerow(["No IP distribution data"])

    # IP percentages
    ip_pct = data.get("ip_percentages", {})
    if ip_pct:
        writer.writerow([])
        writer.writerow(["IP Class", "Percentage (%)"])
        for cls, pct in ip_pct.items():
            writer.writerow([cls, pct])

    # ---- PROTOCOL DISTRIBUTION ----
    section("PROTOCOL DISTRIBUTION")
    proto_dist = data.get("protocol_distribution", {})
    if proto_dist:
        writer.writerow(["Protocol", "Packet Count"])
        for proto, count in sorted(proto_dist.items(), key=lambda x: -x[1]):
            writer.writerow([proto, count])
    else:
        writer.writerow(["No protocol distribution data"])

    # ---- PROTOCOL ACTIVITY TIMELINE ----
    section("PROTOCOL ACTIVITY TIMELINE")
    timeline = data.get("protocol_timeline", {})
    if timeline:
        writer.writerow(["Time Bucket", "Protocol", "Count"])
        for time_bucket, protocols in sorted(timeline.items()):
            # time_bucket is usually an epoch string e.g. "1771234640"
            try:
                human_time = datetime.fromtimestamp(int(time_bucket), tz=timezone.utc).strftime("%H:%M:%S")
            except:
                human_time = time_bucket

            if isinstance(protocols, dict):
                for proto, cnt in protocols.items():
                    writer.writerow([human_time, proto, cnt])
            else:
                writer.writerow([human_time, "—", protocols])
    else:
        writer.writerow(["No protocol timeline data available"])

    # ---- TCP ANALYSIS ----
    section("TCP ANALYSIS")
    tcp = data.get("tcp", {})
    if tcp:
        writer.writerow(["Metric", "Value"])
        writer.writerow(["Total TCP Packets", _na(tcp.get("total_tcp_packets"))])
        writer.writerow(["Graceful Closes (FIN)", _na(tcp.get("graceful_closes"))])
        writer.writerow(["Abrupt Resets (RST)", _na(tcp.get("rst_closes"))])
        writer.writerow(["Timeout Retransmissions", _na(tcp.get("timeout_retransmissions"))])
        writer.writerow(["Fast Retransmissions", _na(tcp.get("fast_retransmissions"))])
        writer.writerow(["Partial Retransmissions", _na(tcp.get("partial_retransmissions"))])
        writer.writerow(["Out-of-Order Packets", _na(tcp.get("out_of_order"))])
        writer.writerow(["Retransmission Rate (%)", _na(tcp.get("retransmission_rate"))])
        writer.writerow(["Severity", _na(tcp.get("severity")).upper()])
        writer.writerow(["Assessment Note", _na(tcp.get("note"))])
    else:
        writer.writerow(["No TCP analysis data available"])

    # ---- LAYER 2 ANALYSIS ----
    section("LAYER 2 ANALYSIS")
    l2_link = data.get("link_layer", {})
    writer.writerow(["Link-Layer Type", _na(l2_link.get("primary"))])
    
    # ARP
    arp = data.get("arp_analysis", {})
    writer.writerow([])
    writer.writerow(["=== ARP ANALYSIS ==="])
    writer.writerow(["Total ARP Packets", _na(arp.get("total_arp_packets"))])
    writer.writerow(["Request/Reply Ratio", _na(arp.get("request_reply_ratio"))])
    spoof = arp.get("potential_spoofing", [])
    if spoof:
        writer.writerow(["POTENTIAL ARP SPOOFING DETECTED"])
        writer.writerow(["IP Address", "Competing MAC Addresses"])
        for s in spoof:
            writer.writerow([_na(s.get("ip")), "| ".join(s.get("macs", []))])

    # VLAN
    vlan = data.get("vlan_analysis", {})
    writer.writerow([])
    writer.writerow(["=== VLAN / 802.1Q ANALYSIS ==="])
    writer.writerow(["Total Tagged Frames", _na(vlan.get("total_tagged_frames"))])
    writer.writerow(["Unique VLAN IDs", _na(vlan.get("unique_vlan_count"))])
    writer.writerow(["QinQ (Double Tagging) Frames", _na(vlan.get("double_tagged_frames"))])

    # STP
    stp = data.get("stp_analysis", {})
    writer.writerow([])
    writer.writerow(["=== STP (802.1D) ANALYSIS ==="])
    writer.writerow(["Total BPDUs", _na(stp.get("total_bpdus"))])
    writer.writerow(["Topology Changes Detected", _na(stp.get("topology_changes"))])

    # ---- SCTP ANALYSIS ----
    section("SCTP ANALYSIS")
    sctp = data.get("sctp_analysis", {})
    if sctp and sctp.get("total_sctp_packets", 0) > 0:
        writer.writerow(["Metric", "Value"])
        writer.writerow(["Total SCTP Packets", _na(sctp.get("total_sctp_packets"))])
        writer.writerow(["Unique Associations", _na(sctp.get("unique_associations"))])
        writer.writerow(["Multi-homing Indicators", _na(sctp.get("multi_homing_indicators"))])
        
        # Chunks
        writer.writerow([])
        writer.writerow(["Chunk Type", "Count"])
        for ct, cnt in sctp.get("chunk_types", {}).items():
            writer.writerow([ct, cnt])
    else:
        writer.writerow(["No SCTP activity detected"])

    # ---- TLS/SSL INSIGHTS ----
    section("TLS/SSL INSIGHTS")
    tls = data.get("tls_metadata", {})
    if tls:
        # Versions
        versions = tls.get("versions", {})
        if versions:
            writer.writerow(["TLS Version", "Connection Count"])
            for v, c in sorted(versions.items(), key=lambda x: -x[1]):
                writer.writerow([v, c])
        # Cipher Suites
        ciphers = tls.get("cipher_suites", {})
        if ciphers:
            writer.writerow([])
            writer.writerow(["Cipher Suite", "Count"])
            for cs, c in sorted(ciphers.items(), key=lambda x: -x[1]):
                writer.writerow([cs, c])
        # SNI Domains
        sni = tls.get("sni_domains", {})
        if sni:
            writer.writerow([])
            writer.writerow(["SNI Domain", "Connection Count"])
            for d, c in sorted(sni.items(), key=lambda x: -x[1]):
                writer.writerow([d, c])
        # JA3 Fingerprints
        ja3 = tls.get("ja3_fingerprints", {})
        if ja3:
            writer.writerow([])
            writer.writerow(["JA3 Fingerprint", "Count"])
            for f, c in sorted(ja3.items(), key=lambda x: -x[1]):
                writer.writerow([f, c])
        # Certificate Issuers
        issuers = tls.get("cert_issuers", {})
        if issuers:
            writer.writerow([])
            writer.writerow(["Certificate Issuer", "Count"])
            for issuer, c in sorted(issuers.items(), key=lambda x: -x[1]):
                writer.writerow([issuer, c])
        # Certificate Subjects
        subjects = tls.get("cert_subjects", {})
        if subjects:
            writer.writerow([])
            writer.writerow(["Certificate Subject (CN)", "Count"])
            for subj, c in sorted(subjects.items(), key=lambda x: -x[1]):
                writer.writerow([subj, c])
    else:
        writer.writerow(["No TLS/SSL metadata available"])

    # ---- HTTP THREAT ANALYSIS ----
    section("HTTP THREAT ANALYSIS (UNENCRYPTED MALICIOUS ACTIVITY)")
    http_threats = data.get("http_threats", [])
    if http_threats:
        writer.writerow(["Threat Type", "Source IP", "Source Port",
                         "Destination IP", "Destination Port",
                         "HTTP Host", "HTTP URI", "Method",
                         "Severity", "Timestamp"])
        for h in http_threats:
            writer.writerow([
                _na(h.get("threat_type")),
                _na(h.get("src_ip")),
                _na(h.get("src_port")),
                _na(h.get("dest_ip")),
                _na(h.get("dest_port")),
                _na(h.get("http_host")),
                _na(h.get("http_uri")),
                _na(h.get("http_method")),
                _na(h.get("severity")),
                _fmt_ts(h.get("timestamp")),
            ])
    else:
        writer.writerow(["No unencrypted HTTP threats detected"])

    # ---- BEHAVIORAL ANOMALY DETECTION ----
    section("BEHAVIORAL ANOMALY DETECTION (TCP)")
    tcp_behavior = data.get("tcp_behavior", {})
    behav_flagged = tcp_behavior.get("flagged_entities", []) if tcp_behavior else []
    if behav_flagged:
        writer.writerow(["Source IP", "Risk Score", "Flags Detected",
                         "Unique Ports Contacted", "Handshake Failure Rate",
                         "Total SYNs", "Failed SYNs"])
        for e in behav_flagged:
            reasons = "; ".join(e.get("reasons", []))
            writer.writerow([
                _na(e.get("ip")),
                _na(e.get("score")),
                _na(reasons),
                _na(e.get("unique_ports")),
                _na(e.get("handshake_failure_rate")),
                _na(e.get("total_syns")),
                _na(e.get("failed_syns")),
            ])
    else:
        writer.writerow(["No behavioral anomalies detected"])

    # ---- UDP ANALYSIS ----
    section("UDP ANALYSIS — SUMMARY")
    udp = data.get("udp_analysis", {})
    udp_summary = udp.get("udp_summary", {}) if udp else {}
    if udp_summary:
        writer.writerow(["Metric", "Value"])
        for k, v in udp_summary.items():
            writer.writerow([str(k).replace("_", " ").title(), _na(v)])
    else:
        writer.writerow(["No UDP summary data available"])

    # UDP status / severity
    udp_status = udp.get("status", "") if udp else ""
    if udp_status:
        writer.writerow(["UDP Status", udp_status.upper()])

    # Top UDP Sources
    top_udp_sources = udp.get("top_udp_sources", []) if udp else []
    if top_udp_sources:
        writer.writerow([])
        writer.writerow(["=== UDP — TOP SOURCES ==="])
        writer.writerow(["Source IP", "Packet Count"])
        for entry in top_udp_sources:
            if isinstance(entry, (list, tuple)) and len(entry) >= 2:
                writer.writerow([entry[0], entry[1]])
            elif isinstance(entry, dict):
                writer.writerow([_na(entry.get("ip")), _na(entry.get("count"))])

    # UDP Port Distribution
    port_dist = udp.get("port_distribution", []) if udp else []
    if port_dist:
        writer.writerow([])
        writer.writerow(["=== UDP — PORT DISTRIBUTION ==="])
        writer.writerow(["Port", "Packet Count"])
        for entry in port_dist:
            if isinstance(entry, (list, tuple)) and len(entry) >= 2:
                writer.writerow([entry[0], entry[1]])
            elif isinstance(entry, dict):
                writer.writerow([_na(entry.get("port")), _na(entry.get("count"))])

    # UDP Flagged / Suspicious Entities
    udp_flagged = udp.get("flagged_entities", []) if udp else []
    udp_suspicious = udp.get("suspicious_entities", []) if udp else []
    all_udp_flagged = udp_flagged + [e for e in udp_suspicious if e not in udp_flagged]
    if all_udp_flagged:
        writer.writerow([])
        writer.writerow(["=== UDP — FLAGGED ENTITIES ==="])
        writer.writerow(["IP Address", "Risk Score", "Flags / Reasons"])
        for e in all_udp_flagged:
            reasons = "; ".join(e.get("reasons", [])) if isinstance(e.get("reasons"), list) else _na(e.get("reasons"))
            writer.writerow([_na(e.get("ip")), _na(e.get("score")), reasons])

    # UDP Priority Targets
    priority = udp.get("priority_targets", []) if udp else []
    if priority:
        writer.writerow([])
        writer.writerow(["=== UDP — PRIORITY TARGETS ==="])
        writer.writerow(["IP Address", "Risk Score", "Reasons"])
        for e in priority:
            reasons = "; ".join(e.get("reasons", [])) if isinstance(e.get("reasons"), list) else _na(e.get("reasons"))
            writer.writerow([_na(e.get("ip")), _na(e.get("score")), reasons])

    # ---- SURICATA IDS ALERTS ----
    section("SURICATA IDS ALERTS & INDICATORS OF COMPROMISE")
    flagged_entities = (data.get("abnormal_activity") or {}).get("flagged_entities", [])
    deduped_alerts = _dedup_alerts(flagged_entities)

    if deduped_alerts:
        writer.writerow([
            "Entity IP", "Signature", "Severity", "Category",
            "SID", "Rev", "Source IP", "Source Port",
            "Destination IP", "Destination Port", "Protocol",
            "Flow ID", "Timestamp"
        ])
        for a in deduped_alerts:
            writer.writerow([
                _na(a.get("_entity_ip")),
                _na(a.get("signature")),
                _sev_label(a.get("severity", 3)),
                _na(a.get("category")),
                _na(a.get("sid")),
                _na(a.get("rev")),
                _na(a.get("src_ip")),
                _na(a.get("src_port")),
                _na(a.get("dest_ip")),
                _na(a.get("dest_port")),
                _na(a.get("proto")),
                _na(a.get("flow_id")),
                _fmt_ts(a.get("timestamp")),
            ])
    else:
        writer.writerow(["No Suricata alerts generated for this capture"])

    # ---- DNS & DOMAIN INTELLIGENCE ----
    section("DNS QUERY LOG")
    domains = data.get("domains", [])
    if domains:
        writer.writerow(["Observed DNS Domain"])
        for d in sorted(set(str(d) for d in domains)):
            writer.writerow([d])
    else:
        writer.writerow(["No DNS queries observed"])

    section("DOMAIN THREAT INTELLIGENCE")
    domain_alerts = data.get("domain_threat_alerts", [])
    if domain_alerts:
        writer.writerow(["Domain", "Source", "Classification", "Context"])
        for a in domain_alerts:
            writer.writerow([
                _na(a.get("domain")),
                _na(a.get("source")),
                _na(a.get("classification")).upper(),
                _na(a.get("context") or a.get("note")),
            ])
    else:
        writer.writerow(["No domain threats detected"])

    # ---- EXTRACTED URLS ----
    section("EXTRACTED HTTP URLs")
    urls = data.get("urls", [])
    if urls:
        writer.writerow(["URL", "Method", "Host", "Source IP", "Destination IP", "Timestamp"])
        for u in urls:
            if isinstance(u, dict):
                writer.writerow([
                    _na(u.get("url") or u.get("uri")),
                    _na(u.get("method")),
                    _na(u.get("host")),
                    _na(u.get("src_ip")),
                    _na(u.get("dest_ip")),
                    _fmt_ts(u.get("timestamp")),
                ])
            else:
                writer.writerow([str(u)])
    else:
        writer.writerow(["No HTTP URLs extracted"])

    # ---- HTTP TRANSACTIONS ----
    section("HTTP TRANSACTIONS")
    http_trans = data.get("http_transactions", [])
    if http_trans:
        writer.writerow(["Stream Index", "Client IP", "Client Port", "Server IP", "Server Port", "Server Host", "Method", "URL"])
        for t in http_trans:
            writer.writerow([
                _na(t.get("stream_index")),
                _na(t.get("client_ip")),
                _na(t.get("client_port")),
                _na(t.get("server_ip")),
                _na(t.get("server_port")),
                _na(t.get("server_host")),
                _na(t.get("method")),
                _na(t.get("url"))
            ])
    else:
        writer.writerow(["No HTTP transactions extracted"])

    # ---- EXTRACTED FILES ----
    section("EXTRACTED FILES")
    extracted_files = data.get("extracted_files", [])
    if extracted_files:
        writer.writerow(["Filename", "Size (Bytes)", "Protocol"])
        for f in extracted_files:
            writer.writerow([_na(f.get("filename")), _na(f.get("size_bytes")), _na(f.get("protocol"))])
    else:
        writer.writerow(["No files extracted"])

    # ---- UNENCRYPTED CREDENTIALS ----
    section("UNENCRYPTED CREDENTIALS")
    extracted_credentials = data.get("extracted_credentials", [])
    if extracted_credentials:
        writer.writerow(["Protocol", "Client", "Server", "Username", "Password Snippet"])
        for c in extracted_credentials:
            writer.writerow([_na(c.get("protocol")), _na(c.get("client")), _na(c.get("server")), _na(c.get("username")), _na(c.get("password_snippet"))])
    else:
        writer.writerow(["No unencrypted credentials extracted"])

    # ---- GEO DATA ----
    section("GEOGRAPHIC IP INTELLIGENCE")
    geo_data = data.get("geo_data", {})
    if geo_data:
        writer.writerow(["IP Address", "Country", "Country Code", "City", "ASN", "Organization"])
        for ip, geo in geo_data.items():
            if isinstance(geo, dict):
                writer.writerow([
                    ip,
                    _na(geo.get("country")),
                    _na(geo.get("country_code")),
                    _na(geo.get("city")),
                    _na(geo.get("asn")),
                    _na(geo.get("org") or geo.get("organization")),
                ])
    else:
        writer.writerow(["No geographic IP data available"])

    # ---- COUNTRY TRAFFIC DISTRIBUTION ----
    section("COUNTRY TRAFFIC DISTRIBUTION")
    country_traffic = data.get("country_traffic", [])
    if country_traffic:
        writer.writerow(["Country", "Packet Count"])
        for entry in country_traffic:
            if isinstance(entry, (list, tuple)) and len(entry) >= 2:
                writer.writerow([entry[0], entry[1]])
            elif isinstance(entry, dict):
                writer.writerow([_na(entry.get("country")), _na(entry.get("count"))])
    else:
        writer.writerow(["No country traffic data available"])

    # ---- TOP SENDERS / RECEIVERS ----
    section("TOP SENDERS (by Packet Count)")
    top_senders = data.get("top_senders", [])
    if top_senders:
        writer.writerow(["IP Address", "Packet Count"])
        for ip, count in top_senders:
            writer.writerow([ip, count])
    else:
        writer.writerow(["No sender data available"])

    section("TOP RECEIVERS (by Packet Count)")
    top_receivers = data.get("top_receivers", [])
    if top_receivers:
        writer.writerow(["IP Address", "Packet Count"])
        for ip, count in top_receivers:
            writer.writerow([ip, count])
    else:
        writer.writerow(["No receiver data available"])

    # ---- MAC VENDOR IDENTIFICATION ----
    section("MAC VENDOR IDENTIFICATION")
    mac_vendors = data.get("mac_vendors", [])
    if mac_vendors:
        # Data is [(vendor_string, count), ...] from Counter.most_common()
        writer.writerow(["Vendor / Manufacturer (OUI Prefix)", "Packet Count"])
        for entry in mac_vendors:
            if isinstance(entry, (list, tuple)) and len(entry) >= 2:
                writer.writerow([_na(entry[0]), _na(entry[1])])
            elif isinstance(entry, dict):
                vendor = entry.get("vendor") or entry.get("manufacturer") or entry.get("mac", "N/A")
                count = entry.get("count", "N/A")
                writer.writerow([_na(vendor), _na(count)])
    else:
        writer.writerow(["No MAC vendor data available"])

    return buf.getvalue().encode("utf-8")


# ===========================================================================
# PDF EXPORT
# ===========================================================================

def build_pdf(data: dict, pcap_filename: str = "unknown.pcap") -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        SimpleDocTemplate, Table, TableStyle, Paragraph,
        Spacer, HRFlowable, PageBreak, KeepTogether
    )
    from reportlab.lib.enums import TA_LEFT, TA_CENTER

    report_id = str(uuid.uuid4())
    timestamp = _now_utc()

    buf = io.BytesIO()

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=1.8 * cm,
        leftMargin=1.8 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2.5 * cm,
        title="PCAP Analysis Report",
        author="Adaptive PCAP Analysis System",
        subject="SOC Threat Intelligence Report",
    )

    C_WHITE     = colors.white
    C_PAGE_BG   = colors.white                    # page background
    C_HEADER_BG = colors.HexColor("#1C3557")      # dark navy — column headers
    C_ROW_ODD   = colors.white                    # odd data rows
    C_ROW_EVEN  = colors.HexColor("#F4F7FB")      # very light blue-grey stripe
    C_ACCENT    = colors.HexColor("#1A5FA8")      # section titles — deep blue
    C_RED       = colors.HexColor("#C0392B")      # HIGH severity
    C_ORANGE    = colors.HexColor("#D35400")      # MEDIUM severity
    C_GREEN     = colors.HexColor("#1E7E45")      # clean / safe
    C_TEXT      = colors.HexColor("#1A1A2E")      # near-black body text
    C_MUTED     = colors.HexColor("#5A6A85")      # secondary / labels
    C_BORDER    = colors.HexColor("#C8D4E3")      # table grid lines
    C_HEAD_TEXT = colors.white                    # header cell text
    C_RED_ROW   = colors.HexColor("#FDECEA")      # HIGH row tint
    C_ORG_ROW   = colors.HexColor("#FEF3E2")      # MEDIUM row tint
    C_COVER_BG  = colors.HexColor("#1C3557")      # cover header band

    PAGE_W = A4[0] - 3.6 * cm

    # --- STYLES ---
    styles = getSampleStyleSheet()

    title_st = ParagraphStyle("TS", fontSize=22, textColor=C_WHITE, spaceAfter=6,
                               fontName="Helvetica-Bold", alignment=TA_CENTER)
    sub_st   = ParagraphStyle("SS", fontSize=10, textColor=colors.HexColor("#A8C4E0"),
                               spaceAfter=4, alignment=TA_CENTER)
    sec_st   = ParagraphStyle("SES", fontSize=12, textColor=C_ACCENT, spaceBefore=14,
                               spaceAfter=5, fontName="Helvetica-Bold")
    body_st  = ParagraphStyle("BS", fontSize=8.5, textColor=C_TEXT, leading=13)
    cell_st  = ParagraphStyle("CS", fontSize=8, textColor=C_TEXT, leading=11,
                               wordWrap="CJK")
    head_st  = ParagraphStyle("HS", fontSize=8, textColor=C_HEAD_TEXT,
                               fontName="Helvetica-Bold", leading=11, wordWrap="CJK")
    small_st = ParagraphStyle("SmS", fontSize=8.5, textColor=C_MUTED, leading=12,
                               fontName="Helvetica-Bold")
    red_st   = ParagraphStyle("RS", fontSize=8, textColor=C_RED,
                               fontName="Helvetica-Bold", leading=11, wordWrap="CJK")
    org_st   = ParagraphStyle("OS", fontSize=8, textColor=C_ORANGE, leading=11, wordWrap="CJK")

    def P(text, style=None):
        return Paragraph(str(text) if text is not None else "N/A", style or cell_st)

    def H(text):
        return Paragraph(str(text), head_st)

    # --- TABLE BUILDER ---
    def make_table(rows, col_widths=None, warn_rows=None):
        if not col_widths:
            n = len(rows[0]) if rows else 1
            col_widths = [PAGE_W / n] * n

        tbl = Table(rows, colWidths=col_widths, repeatRows=1)

        cmds = [
            ("BACKGROUND",    (0, 0), (-1, 0),  C_HEADER_BG),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1),  [C_ROW_ODD, C_ROW_EVEN]),
            ("GRID",          (0, 0), (-1, -1),  0.5, C_BORDER),
            ("LEFTPADDING",   (0, 0), (-1, -1),  5),
            ("RIGHTPADDING",  (0, 0), (-1, -1),  5),
            ("TOPPADDING",    (0, 0), (-1, -1),  4),
            ("BOTTOMPADDING", (0, 0), (-1, -1),  4),
            ("VALIGN",        (0, 0), (-1, -1),  "TOP"),
        ]
        for idx, level in (warn_rows or []):
            bg = C_RED_ROW if level == "high" else C_ORG_ROW
            cmds.append(("BACKGROUND", (0, idx), (-1, idx), bg))
        tbl.setStyle(TableStyle(cmds))
        return tbl

    def kv_table(pairs, left_w=0.42):
        """Two-column key-value table."""
        rows = [[H("Field"), H("Value")]]
        for k, v in pairs:
            rows.append([P(k), P(v)])
        return make_table(rows, col_widths=[PAGE_W * left_w, PAGE_W * (1 - left_w)])

    # --- FOOTER ---
    def add_footer(canvas, doc_obj):
        canvas.saveState()
        t = "Generated by Adaptive PCAP Analysis System  |  CONFIDENTIAL: For Authorized SOC Use Only"
        canvas.setFont("Helvetica", 6.5)
        canvas.setFillColor(C_MUTED)
        canvas.drawCentredString(A4[0] / 2, 1.2 * cm, t)
        canvas.drawRightString(A4[0] - 1.8 * cm, 1.2 * cm, f"Page {doc_obj.page}")
        canvas.restoreState()

    def section_title(n, title):
        return [
            Paragraph(f"{n}. {title}", sec_st),
            HRFlowable(width="100%", thickness=1, color=C_ACCENT),
            Spacer(1, 0.15 * cm),
        ]

    # =====================================================================
    # BUILD STORY
    # =====================================================================
    story = []

    cover_title_st = ParagraphStyle("CT", fontSize=20, textColor=C_WHITE,
                                    fontName="Helvetica-Bold", alignment=TA_CENTER,
                                    spaceAfter=4, leading=26)
    cover_sub_st   = ParagraphStyle("CS2", fontSize=10,
                                    textColor=colors.HexColor("#A8C4E0"),
                                    alignment=TA_CENTER, leading=14)

    cover_content = [
        Spacer(1, 0.3 * cm),
        Paragraph("PCAP ANALYSIS REPORT", cover_title_st),
        Paragraph("Security Operations Center - Threat Intelligence Report", cover_sub_st),
        Spacer(1, 0.3 * cm),
    ]

    cover_tbl = Table([[cover_content]], colWidths=[PAGE_W])
    cover_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), C_COVER_BG),
        ("LEFTPADDING",  (0, 0), (-1, -1), 24),
        ("RIGHTPADDING", (0, 0), (-1, -1), 24),
        ("TOPPADDING",   (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 0),
        ("ROUNDEDCORNERS", [6, 6, 6, 6]),
    ]))
    story.append(cover_tbl)
    story.append(HRFlowable(width="100%", thickness=2.5, color=C_ACCENT, spaceAfter=10))
    story.append(Spacer(1, 0.3 * cm))

    meta = data.get("capture_metadata", {})
    story.append(kv_table([
        ("Report ID", report_id),
        ("Generated At (UTC)", timestamp),
        ("PCAP File", _na(pcap_filename)),
        ("PCAP Format", _na(meta.get("pcap_format"))),
        ("File Size (KB)", _na(meta.get("file_size_kb"))),
        ("Capture Duration (s)", _na(meta.get("capture_duration"))),
        ("Capture Start", _fmt_ts(meta.get("start_time"))),
        ("Capture End", _fmt_ts(meta.get("end_time"))),
        ("Snapshot Length (bytes)", _na(meta.get("snapshot_length"))),
        ("Classification", "CONFIDENTIAL: For Authorized SOC Use Only"),
    ]))
    story.append(Spacer(1, 0.4 * cm))

    # --- 1. EXECUTIVE SUMMARY ---
    story += section_title(1, "Executive Summary")
    flagged_entities = (data.get("abnormal_activity") or {}).get("flagged_entities", [])
    http_threats = data.get("http_threats") or []
    domain_alerts = data.get("domain_threat_alerts") or []
    deduped_alerts = _dedup_alerts(flagged_entities)
    high_alerts = sum(1 for a in deduped_alerts if a.get("severity") == 1)
    total = data.get("total_packets", 0)

    summary = (
        f"This report covers the forensic analysis of <b>{_na(total)}</b> packets captured in "
        f"<b>{_na(pcap_filename)}</b> over a duration of <b>{_na(meta.get('capture_duration'))} seconds</b>. "
        f"The Suricata IDS engine raised <b>{len(deduped_alerts)}</b> unique alert(s) across "
        f"<b>{len(flagged_entities)}</b> entity/entities, including <b>{high_alerts}</b> HIGH severity. "
        f"<b>{len(http_threats)}</b> unencrypted HTTP threat(s) and "
        f"<b>{len(domain_alerts)}</b> suspicious/malicious domain(s) were identified. "
        f"Analysts should prioritize HIGH-severity Suricata alerts and HTTP threat indicators."
    )
    story.append(Paragraph(summary, body_st))
    story.append(Spacer(1, 0.4 * cm))

    # --- 2. TRAFFIC OVERVIEW ---
    story += section_title(2, "Traffic Overview")
    pkt = data.get("packet_size", {})
    story.append(kv_table([
        ("Total Packets", _na(data.get("total_packets"))),
        ("Valid Packets", _na(data.get("valid_packets"))),
        ("Malformed Packets", _na(data.get("malformed_packets"))),
        ("Fragmented Packets", _na(data.get("fragmented_packets"))),
        ("Jumbo Frames (>1500B)", _na(data.get("jumbo_frames"))),
        ("Packets / Second", _na(data.get("packets_per_second"))),
        ("Packet Size — Min (bytes)", _na(pkt.get("min"))),
        ("Packet Size — Max (bytes)", _na(pkt.get("max"))),
        ("Packet Size — Avg (bytes)", _na(pkt.get("avg"))),
    ]))
    story.append(Spacer(1, 0.2 * cm))

    # Packet size histogram
    hist = data.get("packet_size_histogram", {})
    if hist:
        story.append(Paragraph("Packet Size Distribution Histogram", small_st))
        h_rows = [[H("Size Bin"), H("Packet Count")]]
        for bin_lbl, cnt in hist.items():
            h_rows.append([P(bin_lbl), P(str(cnt))])
        story.append(make_table(h_rows, col_widths=[PAGE_W * 0.5, PAGE_W * 0.5]))
    story.append(Spacer(1, 0.4 * cm))

    # --- 3. PROTOCOL & IP ANALYSIS ---
    story += section_title(3, "Protocol & IP Analysis")

    proto_dist = data.get("protocol_distribution", {})
    if proto_dist:
        story.append(Paragraph("Protocol Distribution", small_st))
        p_rows = [[H("Protocol"), H("Packet Count")]]
        for p, c in sorted(proto_dist.items(), key=lambda x: -x[1]):
            p_rows.append([P(p), P(str(c))])
        story.append(make_table(p_rows, col_widths=[PAGE_W * 0.5, PAGE_W * 0.5]))
        story.append(Spacer(1, 0.2 * cm))

    ip_dist = data.get("ip_distribution", {})
    ip_pct = data.get("ip_percentages", {})
    if ip_dist:
        story.append(Paragraph("IP Address Distribution", small_st))
        ip_rows = [[H("IP Class"), H("Packet Count"), H("Percentage")]]
        for cls, cnt in ip_dist.items():
            pct = _na(ip_pct.get(cls))
            ip_rows.append([P(cls), P(str(cnt)), P(pct)])
        story.append(make_table(ip_rows, col_widths=[PAGE_W * 0.4, PAGE_W * 0.3, PAGE_W * 0.3]))
    story.append(Spacer(1, 0.4 * cm))

    # --- 4. TCP ANALYSIS ---
    story += section_title(4, "TCP Analysis")
    tcp = data.get("tcp", {})
    if tcp:
        sev_val = str(tcp.get("severity", "normal")).lower()
        warn_rows = [(8, "high")] if sev_val == "high" else ([(8, "medium")] if sev_val == "medium" else [])
        pairs = [
            ("Total TCP Packets", _na(tcp.get("total_tcp_packets"))),
            ("Timeout Retransmissions", _na(tcp.get("timeout_retransmissions"))),
            ("Fast Retransmissions", _na(tcp.get("fast_retransmissions"))),
            ("Partial Retransmissions", _na(tcp.get("partial_retransmissions"))),
            ("Out-of-Order Packets", _na(tcp.get("out_of_order"))),
            ("Retransmission Rate (%)", _na(tcp.get("retransmission_rate"))),
            ("Severity", _na(tcp.get("severity")).upper()),
            ("Assessment Note", _na(tcp.get("note"))),
        ]
        rows = [[H("Metric"), H("Value")]] + [[P(k), P(v)] for k, v in pairs]
        story.append(make_table(rows, col_widths=[PAGE_W * 0.45, PAGE_W * 0.55],
                                warn_rows=warn_rows))
    else:
        story.append(Paragraph("No TCP analysis data available.", small_st))
    story.append(Spacer(1, 0.4 * cm))

    # --- 5. TLS/SSL INSIGHTS ---
    story += section_title(5, "TLS/SSL Insights")
    tls = data.get("tls_metadata", {})
    if tls:
        versions = tls.get("versions", {})
        if versions:
            story.append(Paragraph("TLS Versions Observed", small_st))
            ver_rows = [[H("TLS Version"), H("Connection Count")]]
            for v, c in sorted(versions.items(), key=lambda x: -x[1]):
                ver_rows.append([P(v), P(str(c))])
            story.append(make_table(ver_rows, col_widths=[PAGE_W * 0.65, PAGE_W * 0.35]))
            story.append(Spacer(1, 0.15 * cm))

        ciphers = tls.get("cipher_suites", {})
        if ciphers:
            story.append(Paragraph("Cipher Suites", small_st))
            cs_rows = [[H("Cipher Suite"), H("Count")]]
            for cs, c in sorted(ciphers.items(), key=lambda x: -x[1]):
                cs_rows.append([P(cs), P(str(c))])
            story.append(make_table(cs_rows, col_widths=[PAGE_W * 0.7, PAGE_W * 0.3]))
            story.append(Spacer(1, 0.15 * cm))

        sni = tls.get("sni_domains", {})
        if sni:
            story.append(Paragraph("SNI Domains (TLS Server Name Indication)", small_st))
            sni_rows = [[H("SNI Domain"), H("Connection Count")]]
            for d, c in sorted(sni.items(), key=lambda x: -x[1]):
                sni_rows.append([P(d), P(str(c))])
            story.append(make_table(sni_rows, col_widths=[PAGE_W * 0.72, PAGE_W * 0.28]))
            story.append(Spacer(1, 0.15 * cm))

        ja3 = tls.get("ja3_fingerprints", {})
        if ja3:
            story.append(Paragraph("JA3 Fingerprints (TLS Client Fingerprinting)", small_st))
            ja3_rows = [[H("JA3 Hash"), H("Count")]]
            for f, c in sorted(ja3.items(), key=lambda x: -x[1]):
                ja3_rows.append([P(f), P(str(c))])
            story.append(make_table(ja3_rows, col_widths=[PAGE_W * 0.78, PAGE_W * 0.22]))
            story.append(Spacer(1, 0.15 * cm))

        issuers = tls.get("cert_issuers", {})
        if issuers:
            story.append(Paragraph("Certificate Issuers", small_st))
            ci_rows = [[H("Issuer"), H("Count")]]
            for issuer, c in sorted(issuers.items(), key=lambda x: -x[1]):
                ci_rows.append([P(issuer), P(str(c))])
            story.append(make_table(ci_rows, col_widths=[PAGE_W * 0.78, PAGE_W * 0.22]))
    else:
        story.append(Paragraph("No TLS/SSL metadata available for this capture.", small_st))
    story.append(Spacer(1, 0.4 * cm))

    # --- 6. LAYER 2 ANALYSIS ---
    story += section_title(6, "Layer 2 Analysis (Data Link)")
    l2_link = data.get("link_layer", {})
    l2_rows = [
        [H("Metric"), H("Value")],
        [P("Link-Layer Type"), P(_na(l2_link.get("primary")))]
    ]
    story.append(make_table(l2_rows, col_widths=[PAGE_W * 0.45, PAGE_W * 0.55]))
    story.append(Spacer(1, 0.2 * cm))

    # ARP
    arp = data.get("arp_analysis", {})
    story.append(Paragraph("ARP Protocol Analysis", small_st))
    arp_rows = [
        [H("ARP Metric"), H("Value")],
        [P("Total ARP Packets"), P(_na(arp.get("total_arp_packets")))],
        [P("Request/Reply Ratio"), P(_na(arp.get("request_reply_ratio")))]
    ]
    story.append(make_table(arp_rows, col_widths=[PAGE_W * 0.45, PAGE_W * 0.55]))
    
    spoof = arp.get("potential_spoofing", [])
    if spoof:
        story.append(Spacer(1, 0.1 * cm))
        story.append(Paragraph("POTENTIAL ARP SPOOFING DETECTED", red_st))
        s_rows = [[H("IP Address"), H("Competing MAC Addresses")]]
        for s in spoof:
            s_rows.append([P(s.get("ip")), P("| ".join(s.get("macs", [])))])
        story.append(make_table(s_rows, col_widths=[PAGE_W * 0.4, PAGE_W * 0.6], warn_rows=[(i, "high") for i in range(1, len(s_rows))]))
    story.append(Spacer(1, 0.3 * cm))

    # VLAN & STP
    v_rows = [[H("VLAN Metric"), H("Value"), H("STP Metric"), H("Value")]]
    vlan = data.get("vlan_analysis", {})
    stp = data.get("stp_analysis", {})
    v_rows.append([
        P("Tagged Frames"), P(_na(vlan.get("total_tagged_frames"))),
        P("Total BPDUs"), P(_na(stp.get("total_bpdus")))
    ])
    v_rows.append([
        P("VLAN IDs"), P(_na(vlan.get("unique_vlan_count"))),
        P("Topo Changes"), P(_na(stp.get("topology_changes")))
    ])
    story.append(make_table(v_rows, col_widths=[PAGE_W * 0.25, PAGE_W * 0.25, PAGE_W * 0.25, PAGE_W * 0.25]))
    story.append(Spacer(1, 0.4 * cm))

    # --- 7. SCTP ANALYSIS ---
    sctp = data.get("sctp_analysis", {})
    if sctp and sctp.get("total_sctp_packets", 0) > 0:
        story += section_title(7, "SCTP Protocol Analysis")
        s_rows = [
            [H("Metric"), H("Value")],
            [P("Total SCTP Packets"), P(_na(sctp.get("total_sctp_packets")))],
            [P("Unique Associations"), P(_na(sctp.get("unique_associations")))],
            [P("Multi-homing Indicators"), P(_na(sctp.get("multi_homing_indicators")))]
        ]
        story.append(make_table(s_rows, col_widths=[PAGE_W * 0.45, PAGE_W * 0.55]))
        
        chunks = sctp.get("chunk_types", {})
        if chunks:
            story.append(Spacer(1, 0.2 * cm))
            story.append(Paragraph("Chunk Type Distribution", small_st))
            c_rows = [[H("Chunk Type"), H("Count")]]
            for ct, cnt in chunks.items():
                c_rows.append([P(ct), P(str(cnt))])
            story.append(make_table(c_rows, col_widths=[PAGE_W * 0.5, PAGE_W * 0.5]))
        story.append(Spacer(1, 0.4 * cm))

    # --- 8. HTTP THREAT ANALYSIS ---
    story.append(PageBreak())
    story += section_title(8, "HTTP Threat Analysis (Unencrypted Malicious Activity)")
    if http_threats:
        http_rows = [[H("Threat Type"), H("Src IP"), H("Dst IP"), H("Host"), H("URI"), H("Sev.")]]
        warn_rows_http = []
        for i, h in enumerate(http_threats, 1):
            sev = str(h.get("severity", "")).lower()
            s = ParagraphStyle("hs", fontSize=7.5, textColor=(C_RED if sev == "high" else C_ORANGE if sev == "medium" else C_TEXT),
                               fontName="Helvetica-Bold", leading=11, wordWrap="CJK")
            http_rows.append([
                P(h.get("threat_type")),
                P(h.get("src_ip")),
                P(h.get("dest_ip")),
                P(h.get("http_host")),
                P(h.get("http_uri")),
                Paragraph(str(h.get("severity", "N/A")).upper(), s),
            ])
            if sev == "high": warn_rows_http.append((i, "high"))
            elif sev == "medium": warn_rows_http.append((i, "medium"))
        cw = [PAGE_W * x for x in [0.18, 0.14, 0.14, 0.22, 0.24, 0.08]]
        story.append(make_table(http_rows, col_widths=cw, warn_rows=warn_rows_http))
    else:
        story.append(Paragraph("No unencrypted HTTP threats detected.", small_st))
    story.append(Spacer(1, 0.4 * cm))

    # --- 9. BEHAVIORAL ANOMALY DETECTION ---
    story += section_title(9, "Behavioral Anomaly Detection (TCP)")
    behav_flagged = (data.get("tcp_behavior") or {}).get("flagged_entities", [])
    if behav_flagged:
        b_rows = [[H("IP Address"), H("Risk Score"), H("Flags Detected"), H("Unique Ports"), H("HS Fail Rate")]]
        warn_b = []
        for i, e in enumerate(behav_flagged, 1):
            score = e.get("score", 0)
            reasons = "; ".join(e.get("reasons", []))
            b_rows.append([P(e.get("ip")), P(str(score)), P(reasons),
                           P(e.get("unique_ports")), P(e.get("handshake_failure_rate"))])
            if score >= 70: warn_b.append((i, "high"))
            elif score >= 40: warn_b.append((i, "medium"))
        cw = [PAGE_W * x for x in [0.19, 0.10, 0.43, 0.14, 0.14]]
        story.append(make_table(b_rows, col_widths=cw, warn_rows=warn_b))
    else:
        story.append(Paragraph("No behavioral anomalies detected.", small_st))
    story.append(Spacer(1, 0.4 * cm))

    # --- 10. UDP ANALYSIS ---
    story += section_title(10, "UDP Analysis")
    udp = data.get("udp_analysis") or {}
    udp_summary = udp.get("udp_summary", {})
    if udp_summary:
        story.append(Paragraph("UDP Summary", small_st))
        udp_pairs = [[H("Metric"), H("Value")]]
        for k, v in udp_summary.items():
            udp_pairs.append([P(str(k).replace("_", " ").title()), P(str(v))])
        story.append(make_table(udp_pairs, col_widths=[PAGE_W * 0.55, PAGE_W * 0.45]))
        story.append(Spacer(1, 0.15 * cm))

    top_udp = udp.get("top_udp_sources", [])
    if top_udp:
        story.append(Paragraph("Top UDP Sources", small_st))
        u_rows = [[H("Source IP"), H("Packet Count")]]
        for entry in top_udp[:30]:
            if isinstance(entry, (list, tuple)):
                u_rows.append([P(entry[0]), P(str(entry[1]))])
            elif isinstance(entry, dict):
                u_rows.append([P(entry.get("ip")), P(str(entry.get("count")))])
        story.append(make_table(u_rows, col_widths=[PAGE_W * 0.65, PAGE_W * 0.35]))
        story.append(Spacer(1, 0.15 * cm))

    port_dist = udp.get("port_distribution", [])
    if port_dist:
        story.append(Paragraph("UDP Port Distribution", small_st))
        pd_rows = [[H("Port"), H("Packet Count")]]
        for entry in port_dist[:40]:
            if isinstance(entry, (list, tuple)):
                pd_rows.append([P(str(entry[0])), P(str(entry[1]))])
            elif isinstance(entry, dict):
                pd_rows.append([P(str(entry.get("port"))), P(str(entry.get("count")))])
        story.append(make_table(pd_rows, col_widths=[PAGE_W * 0.5, PAGE_W * 0.5]))
        story.append(Spacer(1, 0.15 * cm))

    udp_flagged = (udp.get("flagged_entities") or []) + [
        e for e in (udp.get("suspicious_entities") or [])
        if e not in (udp.get("flagged_entities") or [])
    ]
    if udp_flagged:
        story.append(Paragraph("UDP Flagged / Suspicious Entities", small_st))
        uf_rows = [[H("IP Address"), H("Risk Score"), H("Flags / Reasons")]]
        uf_warn = []
        for i, e in enumerate(udp_flagged, 1):
            score = e.get("score", 0)
            reasons = "; ".join(e.get("reasons", [])) if isinstance(e.get("reasons"), list) else _na(e.get("reasons"))
            uf_rows.append([P(e.get("ip")), P(str(score)), P(reasons)])
            if score >= 70: uf_warn.append((i, "high"))
            elif score >= 40: uf_warn.append((i, "medium"))
        cw = [PAGE_W * x for x in [0.22, 0.12, 0.66]]
        story.append(make_table(uf_rows, col_widths=cw, warn_rows=uf_warn))
    story.append(Spacer(1, 0.4 * cm))

    # --- 11. SURICATA IDS ALERTS ---
    story.append(PageBreak())
    story += section_title(11, "Suricata IDS Alerts")
    if deduped_alerts:
        a_rows = [[H("Signature"), H("Sev."), H("Category"), H("Src IP:Port"), H("Dst IP:Port"), H("Timestamp")]]
        a_warn = []
        for i, a in enumerate(deduped_alerts, 1):
            sev_int = a.get("severity", 3)
            sev_lbl = _sev_label(sev_int)
            sev_colour = C_RED if sev_int == 1 else (C_ORANGE if sev_int == 2 else C_TEXT)
            sev_s = ParagraphStyle("svs", fontSize=7.5, textColor=sev_colour,
                                   fontName="Helvetica-Bold", leading=11, wordWrap="CJK")
            a_rows.append([
                P(a.get("signature")),
                Paragraph(sev_lbl, sev_s),
                P(a.get("category")),
                P(f"{_na(a.get('src_ip'))}:{_na(a.get('src_port'))}"),
                P(f"{_na(a.get('dest_ip'))}:{_na(a.get('dest_port'))}"),
                P(_fmt_ts(a.get("timestamp"))),
            ])
            if sev_int == 1: a_warn.append((i, "high"))
            elif sev_int == 2: a_warn.append((i, "medium"))
        cw = [PAGE_W * x for x in [0.32, 0.07, 0.20, 0.16, 0.16, 0.09]]
        story.append(make_table(a_rows, col_widths=cw, warn_rows=a_warn))
    else:
        story.append(Paragraph("No Suricata alerts generated for this capture.", small_st))
    story.append(Spacer(1, 0.4 * cm))

    # --- 12. DNS & DOMAIN INTELLIGENCE ---
    story += section_title(12, "DNS & Domain Threat Intelligence")
    if domain_alerts:
        d_rows = [[H("Domain"), H("Source"), H("Classification")]]
        d_warn = []
        for i, a in enumerate(domain_alerts, 1):
            cls = str(a.get("classification", "")).lower()
            cls_s = red_st if cls == "malicious" else (org_st if "suspicious" in cls else cell_st)
            d_rows.append([P(a.get("domain")), P(a.get("source")),
                           Paragraph(_na(a.get("classification")).upper(), cls_s)])
            if cls == "malicious": d_warn.append((i, "high"))
            elif "suspicious" in cls: d_warn.append((i, "medium"))
        story.append(make_table(d_rows, col_widths=[PAGE_W * 0.52, PAGE_W * 0.22, PAGE_W * 0.26],
                                warn_rows=d_warn))
    else:
        domains = data.get("domains", [])
        if domains:
            story.append(Paragraph(f"{len(domains)} DNS domain(s) observed — no threats detected.", body_st))
        else:
            story.append(Paragraph("No DNS queries observed in this capture.", small_st))

    story.append(Spacer(1, 0.2 * cm))
    # DNS log (first 50)
    domains = data.get("domains", [])
    if domains:
        story.append(Paragraph(f"Observed DNS Queries (showing up to 50 of {len(domains)})", small_st))
        dn_rows = [[H("Domain Name")]]
        for d in sorted(set(str(d) for d in domains))[:50]:
            dn_rows.append([P(d)])
        story.append(make_table(dn_rows, col_widths=[PAGE_W]))
    story.append(Spacer(1, 0.4 * cm))

    # --- 13. TOP SENDERS & RECEIVERS ---
    story += section_title(13, "Top Senders & Receivers")
    top_senders   = data.get("top_senders", [])
    top_receivers = data.get("top_receivers", [])

    if top_senders or top_receivers:
        left_rows  = [[H("Source IP"), H("Packets")]] + [[P(ip), P(str(cnt))] for ip, cnt in top_senders[:30]]
        right_rows = [[H("Dest IP"),   H("Packets")]] + [[P(ip), P(str(cnt))] for ip, cnt in top_receivers[:30]]

        # Pad to equal length
        while len(left_rows) < len(right_rows):
            left_rows.append([P("—"), P("—")])
        while len(right_rows) < len(left_rows):
            right_rows.append([P("—"), P("—")])

        combined = []
        for ls, rs in zip(left_rows, right_rows):
            combined.append(ls + rs)

        w2 = PAGE_W / 4
        story.append(make_table(combined, col_widths=[w2 * 1.6, w2 * 0.4, w2 * 1.6, w2 * 0.4]))
    else:
        story.append(Paragraph("No sender/receiver data available.", small_st))
    story.append(Spacer(1, 0.4 * cm))

    # --- 14. COUNTRY TRAFFIC ---
    story += section_title(14, "Country Traffic Distribution")
    ct = data.get("country_traffic", [])
    if ct:
        ct_rows = [[H("Country"), H("Packet Count")]]
        for entry in ct:
            if isinstance(entry, (list, tuple)):
                ct_rows.append([P(str(entry[0])), P(str(entry[1]))])
            elif isinstance(entry, dict):
                ct_rows.append([P(entry.get("country")), P(str(entry.get("count")))])
        story.append(make_table(ct_rows, col_widths=[PAGE_W * 0.65, PAGE_W * 0.35]))
    else:
        story.append(Paragraph("No country traffic data available.", small_st))
    story.append(Spacer(1, 0.4 * cm))

    # --- 15. MAC VENDOR IDENTIFICATION ---
    story += section_title(15, "MAC Vendor Identification")
    mac_vendors = data.get("mac_vendors", [])
    if mac_vendors:
        # Data is [(vendor_string, count), ...] from Counter.most_common()
        mv_rows = [[H("Vendor / Manufacturer (OUI Prefix)"), H("Packet Count")]]
        for entry in mac_vendors:
            if isinstance(entry, (list, tuple)) and len(entry) >= 2:
                mv_rows.append([P(str(entry[0])), P(str(entry[1]))])
            elif isinstance(entry, dict):
                vendor = entry.get("vendor") or entry.get("manufacturer") or entry.get("mac", "N/A")
                count = entry.get("count", "N/A")
                mv_rows.append([P(str(vendor)), P(str(count))])
        story.append(make_table(mv_rows, col_widths=[PAGE_W * 0.70, PAGE_W * 0.30]))
    else:
        story.append(Paragraph("No MAC vendor data available.", small_st))

    story.append(Spacer(1, 0.4 * cm))

    # --- 16. EXTRACTED FILES ---
    story += section_title(16, "Extracted Files")
    extracted_files = data.get("extracted_files", [])
    if extracted_files:
        ef_rows = [[H("Filename"), H("Protocol"), H("Size (Bytes)")]]
        for f in extracted_files:
            ef_rows.append([P(str(f.get("filename"))), P(str(f.get("protocol"))), P(str(f.get("size_bytes")))])
        story.append(make_table(ef_rows, col_widths=[PAGE_W * 0.60, PAGE_W * 0.20, PAGE_W * 0.20]))
    else:
        story.append(Paragraph("No files extracted.", small_st))
        
    story.append(Spacer(1, 0.4 * cm))

    # --- 17. HTTP TRANSACTIONS ---
    story += section_title(17, "HTTP Transactions")
    http_trans = data.get("http_transactions", [])
    if http_trans:
        ht_rows = [[H("Client"), H("Server Host"), H("Method"), H("URL")]]
        for t in http_trans:
            ht_rows.append([
                P(f"{_na(t.get('client_ip'))}:{_na(t.get('client_port'))}"),
                P(_na(t.get("server_host"))),
                P(_na(t.get("method"))),
                P(_na(t.get("url"))),
            ])
        story.append(make_table(ht_rows, col_widths=[PAGE_W * 0.25, PAGE_W * 0.20, PAGE_W * 0.15, PAGE_W * 0.40]))
    else:
        story.append(Paragraph("No HTTP transactions extracted.", small_st))
        
    story.append(Spacer(1, 0.4 * cm))

    # --- 18. UNENCRYPTED CREDENTIALS ---
    story += section_title(18, "Unencrypted Credentials")
    extracted_credentials = data.get("extracted_credentials", [])
    if extracted_credentials:
        ec_rows = [[H("Protocol"), H("Client"), H("Server"), H("Username"), H("Password Snippet")]]
        for c in extracted_credentials:
            ec_rows.append([P(str(c.get("protocol"))), P(str(c.get("client"))), P(str(c.get("server"))), P(str(c.get("username"))), P(str(c.get("password_snippet")))])
        story.append(make_table(ec_rows, col_widths=[PAGE_W * 0.15, PAGE_W * 0.20, PAGE_W * 0.20, PAGE_W * 0.20, PAGE_W * 0.25]))
    else:
        story.append(Paragraph("No unencrypted credentials extracted.", small_st))

    story.append(Spacer(1, 0.6 * cm))
    story.append(HRFlowable(width="100%", thickness=1, color=C_ACCENT))
    story.append(Spacer(1, 0.25 * cm))
    story.append(Paragraph(
        "This report was automatically generated by the Adaptive PCAP Analysis System. "
        "All findings must be validated by a qualified SOC analyst before acting on them.",
        small_st
    ))

    doc.build(story, onFirstPage=add_footer, onLaterPages=add_footer)
    return buf.getvalue()


small_st = None